export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Sidebar from '@/components/Sidebar/Sidebar';
import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  
      <body className='flex'>
        <div className="flex flex-col">
          <Sidebar/>
        </div>

        <div className='w-[100%] h-[100%]'>
          {children}
        </div>
      </body>
    </html>
  )
}
